# RL basics

Термины и понятия:

- агент/среда
- наблюдение $o$ / состояние $s$
- действие $a$, стратегия $\pi: \pi(s) \rightarrow a$ функция перехода $T: T(s, a) \rightarrow s'$
- вознаграждение $r$, ф-я вознаграждений $R: R(s, a) \rightarrow r$
- цикл взаимодействия, траектория $\tau: (s_0, a_0, r_0, s_1, a_1, r_1, ..., s_T, a_T, r_T)$, эпизод
- отдача $G$, подсчет отдачи, средняя[/ожидаемая] отдача $\mathbb{E}[G]$

In [1]:
try:
    import google.colab
    COLAB = True
except ModuleNotFoundError:
    COLAB = False
    pass

if COLAB:
    !pip -q install "gymnasium[classic-control, atari, accept-rom-license]"
    !pip -q install piglet
    !pip -q install imageio_ffmpeg
    !pip -q install moviepy==1.0.3

In [2]:
import glob
import io
import base64
import gymnasium as gym
import numpy as np
from IPython import display as ipythondisplay
from IPython.display import HTML
import matplotlib.pyplot as plt
%matplotlib inline

## Agent, environment

<img src=https://gymnasium.farama.org/_images/lunar_lander.gif caption="lunar lander" width="150" height="50"><img src=https://gymnasium.farama.org/_images/mountain_car.gif caption="mountain car" width="150" height="50">
<img src=https://gymnasium.farama.org/_images/cliff_walking.gif caption="cliff walking" width="300" height="50">
<img src=https://ale.farama.org/_images/montezuma_revenge.gif caption="montezuma revenge" width="150" height="100">
<img src=https://github.com/danijar/crafter/raw/main/media/video.gif caption="crafter" width="150" height="100">
<img src=https://camo.githubusercontent.com/6df2ca438d8fe8aa7a132b859315147818c54af608f8609320c3c20e938acf48/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f344e78376759694d394e44724d724d616f372f67697068792e676966 caption="malmo minecraft" width="150" height="100">
<img src=https://images.ctfassets.net/kftzwdyauwt9/e0c0947f-1a44-4528-4a41450a9f0a/2d0e85871d58d02dbe01b2469d693d4a/table-03.gif caption="roboschool" width="150" height="100">
<img src=https://raw.githubusercontent.com/Tviskaron/mipt/master/2019/RL/02/mdp.png caption="Марковский процесс принятия решений" width="150" height="100">
<img src=https://minigrid.farama.org/_images/DoorKeyEnv.gif caption="minigrid" width="120" height="120">

## Observation, state

TODO:
- добавить примеры наблюдений/состояний (числа, векторы, картинки)
- интуитивное объяснение различия, положить пока, что наблюдение = состояние
- пространство состояний


В каждый момент времени среда имеет некоторое внутреннее состояние. Здесь слово "состояние" я употребил скорее в интуитивном понимании, чтобы обозначить, что среда изменчива (иначе какой смысл с ней взаимодействовать, если ничего не меняется). В обучении с подкреплением под термином состояние $s$ (или $s_t$, где $t$ — текущее время) подразумевают либо абстрактно информацию о "состоянии" среды, либо ее явное представление в виде данных, достаточные для полного описания "состояния". *NB: Здесь можно провести аналогию с компьютерными играми — файл сохранения игры как раз содержит информацию о "состоянии" мира игры, чтобы в будущем можно было продолжить с текущей точки, так что данные этого файла в целом можно с некоторой натяжкой считать состоянием (с натяжкой, потому что редко когда в сложных играх файлы сохранения содержат прямо вот всю информацию, так что после перезагрузки вы получите не совсем точную копию). При этом обычно подразумевается, что состояние не содержит в себе ничего лишнего, то есть это **минимальный** набор информации.*

Наблюдением $o$ называют то, что агент "видит" о текущем состоянии среды. Это не обязательно зрение, а вообще вся доступная ему информация (условно, со всех его органов чувств).

В общем случае наблюдение: кортеж/словарь многомерных векторов чисел.

In [3]:
print(gym.make("CartPole-v1").reset()[0].shape)
print(gym.make("MountainCar-v0").reset()[0].shape)

(4,)
(2,)


## Action, policy, transition function

Рассмотрим следующие MDP:

- A: <img src=https://i.ibb.co/mrCMVZLQ/mdp-a.png caption="A" width="400" height="100">
- B: <img src=https://i.ibb.co/GQ2tVtjC/mdp-b.png caption="B" width="400" height="100">

Links to all:
[A](https://i.ibb.co/mrCMVZLQ/mdp-a.png)
[B](https://i.ibb.co/GQ2tVtjC/mdp-b.png)
[C](https://i.ibb.co/Jj9LYHjP/mdp-c.png)
[D](https://i.ibb.co/Y47Mr83b/mdp-d.png)
[E](https://i.ibb.co/Kjt1Xhmf/mdp-e.png)

Давайте явно запишем пространства состояний $S$ и действий $A$, а также функцию перехода $T$ среды.

In [4]:
states = set(range(3))
actions = set(range(1))

print(f'{states=} | {actions=}')

T = {
    (0, 0): 1,
    (1, 0): 2,
    (2, 0): 2
}
print(f'Transition function {T=}')

A_mdp = states, actions, T

states={0, 1, 2} | actions={0}
Transition function T={(0, 0): 1, (1, 0): 2, (2, 0): 2}


Попробуйте записать функцию перехода в матричном виде:

In [5]:
n_actions = len(actions)
n_states = len(states)
P = np.zeros((n_actions, n_states, n_states))
for (s0, a), s1 in T.items():
    P[a, s0, s1] = 1
print("Matrix form of transition function:\n", P)

Matrix form of transition function:
 [[[0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 1.]]]


Как получить вероятность нахождения агента в состоянии (1) через N шагов? Что происходит с вероятностями нахождения в состояниях при $N \rightarrow \infty$

**Ответ:**
Чтобы получить распределение вероятностей по состояниям после $N$ шагов, мы берем вектор исходного состояния $p_0$ (вероятности или one-hot для детерминированного случая) и умножаем его на матрицу соотвествующую определенному действию. Т.е. если $N$ шагов включали себя $a_1, a_2, ..., a_N$, то искомое распределение будет $p_0 \cdot P[a_1] \cdot P[a_2] \cdot ... \cdot P[a_N]$.

Для случая (А) мы имеем только одно возможное действие для всех состояний, т.е. будет достаточно возвести матрицу в степерь $N$.

In [6]:
p0 = np.array([1, 0, 0])
for N in range(5):
    print(f"Distribution of step #{N}", p0 @ np.linalg.matrix_power(P[0], N))

Distribution of step #0 [1. 0. 0.]
Distribution of step #1 [0. 1. 0.]
Distribution of step #2 [0. 0. 1.]
Distribution of step #3 [0. 0. 1.]
Distribution of step #4 [0. 0. 1.]


In [7]:
p0 = np.array([0.5, 0.2, 0.3])
for N in range(5):
    print(f"Distribution of step #{N}", p0 @ np.linalg.matrix_power(P[0], N))

Distribution of step #0 [0.5 0.2 0.3]
Distribution of step #1 [0.  0.5 0.5]
Distribution of step #2 [0. 0. 1.]
Distribution of step #3 [0. 0. 1.]
Distribution of step #4 [0. 0. 1.]


Также можно заметить, что при $N \rightarrow \infty$ в случае (A) у нас к 3-му шагу всегда сходимость независимо от стартового состояния.

Задайте еще несколько MDP:

- C: <img src=https://i.ibb.co/Jj9LYHjP/mdp-c.png caption="C" width="400" height="100">

In [8]:
states_C = set(range(4))
actions_C = set(range(2))

print(f'{states=} | {actions=}')

T_C = {
    (0, 0): 1,
    (0, 1): 2,
    (1, 0): 1,
    (1, 1): 3,
    (2, 0): 3,
    (2, 1): 2,
    (3, 0): 3,
    (3, 1): 3
}
print(f'Transition function T={T_C}')

A_mdp_C = states_C, actions_C, T_C

states={0, 1, 2} | actions={0}
Transition function T={(0, 0): 1, (0, 1): 2, (1, 0): 1, (1, 1): 3, (2, 0): 3, (2, 1): 2, (3, 0): 3, (3, 1): 3}


In [9]:
n_actions_C = len(actions_C)
n_states_C = len(states_C)
P_C = np.zeros((n_actions_C, n_states_C, n_states_C))
for (s0, a), s1 in T_C.items():
    P_C[a, s0, s1] = 1
print("Matrix form of transition function:\n", P_C)

Matrix form of transition function:
 [[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]


Давайте попробуем задать двух агентов: случайного и оптимального (для каждой среды свой).

In [10]:
class Agent:
    def __init__(self, actions):
        self.rng = np.random.default_rng()
        self.actions = np.array(list(actions))

    def act(self, state):
        return self.rng.integers(len(self.actions))

В качестве дополнения, запишите стратегию агента

В случае (A) случайный и оптимальный агент работают одинаково. Ниже представлена стратегия оптимального агента для (С) из предположения, что $s_3$ - терминальное состояние.

In [11]:
class OptimalAgent:
    def __init__(self, actions):
        policy = {0: 0, 1: 1, 2: 0}
        self.actions = np.array(list(actions))

    def act(self, state):
        return policy[state]

## Reward, reward function

Теперь добавим произвольную функцию вознаграждения. Например, для A:

In [12]:
R = {
    (0, 0): -0.1,
    (1, 0): 1.0,
    (2, 0): 0.0
}
print(R)

A_mdp = *A_mdp, R
print(A_mdp)

{(0, 0): -0.1, (1, 0): 1.0, (2, 0): 0.0}
({0, 1, 2}, {0}, {(0, 0): 1, (1, 0): 2, (2, 0): 2}, {(0, 0): -0.1, (1, 0): 1.0, (2, 0): 0.0})


## Interaction loop, trajectory, termination, truncation, episode

Общий цикл взаимодействия в рамках эпизода:
1. Инициализировать среду: $s \leftarrow \text{env.init()}$
2. Цикл:
    - выбрать действие: $a \leftarrow \pi(s)$
    - получить ответ от среды: $s, r, d \leftarrow \text{env.next(a)}$
    - если $d == \text{True}$, выйти из цикла

In [13]:
def run_episode(mdp):
    states, actions, T, R = mdp
    agent = Agent(actions)

    s = 0
    tau = []
    for _ in range(5):
        a = agent.act(s)
        s_next = T[(s, a)]
        r = R[(s, a)]

        tau.append((s, a, r))
        s = s_next

    return tau

run_episode(A_mdp)

[(0, 0, -0.1), (1, 0, 1.0), (2, 0, 0.0), (2, 0, 0.0), (2, 0, 0.0)]

Termination — означает окончание эпизода, когда достигнуто терминальное состояние. Является частью задания среды.

Truncation — означает окончание эпизода, когда достигнут лимит по числу шагов (=времени). Обычно является внешне заданным параметром для удобства обучения.

Пока не будем вводить truncation, но поддержим termination: расширьте определение среды информацией о терминальных состояниях для всех описанных ранее сред. Сгенерируйте по несколько случайных траекторий для каждой среды.

### Return, expected return

Наиболее важная метрика оценки качества работы агента: отдача.

Отдача: $G(s_t) = \sum_{i=t}^T r_i$

Обычно также вводят параметр $\gamma \in [0, 1]$, дисконтирующий будущие вознаграждения. А еще, тк отдача может меняться от запуска к запуску благодаря вероятностным процессам, нас интересует отдача в среднем — ожидаемая отдача:

$$\hat{G}(s_t) = \mathbb{E} [ \sum_{i=t}^T \gamma^{i-t} r_i ]$$

Именно ее и оптимизируют в RL.

Давайте научимся считать отдачу для состояний по траектории и считать среднюю отдачу.

In [14]:
gamma = 0.9
tau = run_episode(A_mdp)
rewards = [sar[2] for sar in tau]
rewards

[-0.1, 1.0, 0.0, 0.0, 0.0]

In [15]:
G = 0
G_hat = 0
for i, r in enumerate(rewards):
    G += r
    G_hat += r * gamma ** i

In [16]:
G, G_hat

(0.9, 0.8)